[project]
name = "amphimixis"
version = "0.1.0"
description = "Build automation and profiling tool for Linux projects across varios architectures."
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pyyaml"
]

[tool.setuptools]
packages = ["amphimixis", "amphimixis.general", "amphimixis.shell"]
py-modules = ["amphimixis_cli"]

[dependency-groups]
dev = [
    "ruff",
    "black",
    "mypy",
    "pylint",
    "types-paramiko",
    "types-pyyaml",
]

[tool.uv]
package = true

[project.scripts]
amixis = "amphimixis_cli:main"
