[project]
name = "amphimixis"
version = "0.1.0"
description = "Build automation and profiling tool for Linux projects across various architectures."
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pyyaml",
]

[tool.setuptools]
py-modules = ["amixis"]

[tool.setuptools.packages.find]
include = ["amphimixis*"]

[dependency-groups]
dev = [
    "docker",
    "testcontainers",
    "pytest",
    "ruff",
    "black",
    "mypy",
    "pylint",
    "types-paramiko",
    "types-pyyaml",
    "types-docker",
]

[tool.uv]
package = true

[tool.mypy]
disable_error_code = ["import-untyped"]

[project.scripts]
amixis = "amixis:main"
